using System;
using System.Collections.Generic;
using System.Text;

namespace Country_And_States_Telephone_Codes
{
    public class CountryAndPhoneCodeData
    {
        private static Dictionary<string, string> CountryAndPhoneCodeDataMethod()
        {
            Dictionary<string, string> listOfCountryCodes = new Dictionary<string, string>();
            listOfCountryCodes.Add("afghanistan", "93");
            listOfCountryCodes.Add("albania", "355");
            listOfCountryCodes.Add("algeria", "213");
            listOfCountryCodes.Add("american samoa", "1-684");
            listOfCountryCodes.Add("andorra", "376");
            listOfCountryCodes.Add("angola", "244");
            listOfCountryCodes.Add("anguilla", "1-264");
            listOfCountryCodes.Add("antarctica", "672");
            listOfCountryCodes.Add("antigua and Barbuda", "1-268");
            listOfCountryCodes.Add("argentina", "54");
            listOfCountryCodes.Add("armenia", "374");
            listOfCountryCodes.Add("aruba", "297");
            listOfCountryCodes.Add("australia", "61");
            listOfCountryCodes.Add("austria", "43");
            listOfCountryCodes.Add("azerbaijan", "994");
            listOfCountryCodes.Add("bahamas", "1-242");
            listOfCountryCodes.Add("bahrain", "973");
            listOfCountryCodes.Add("bangladesh", "880");
            listOfCountryCodes.Add("barbados", "1-246");
            listOfCountryCodes.Add("belarus", "375");
            listOfCountryCodes.Add("belgium", "32");
            listOfCountryCodes.Add("belize", "501");
            listOfCountryCodes.Add("benin", "229");
            listOfCountryCodes.Add("bermuda", "1-441");
            listOfCountryCodes.Add("bhutan", "975");
            listOfCountryCodes.Add("bolivia", "591");
            listOfCountryCodes.Add("bosnia and herzegovina", "387");
            listOfCountryCodes.Add("botswana", "267");
            listOfCountryCodes.Add("brazil", "55");
            listOfCountryCodes.Add("british indian ocean territory", "246");
            listOfCountryCodes.Add("british virgin islands", "1-284");
            listOfCountryCodes.Add("brunei", "673");
            listOfCountryCodes.Add("bulgaria", "359");
            listOfCountryCodes.Add("burkina Faso", "226");
            listOfCountryCodes.Add("burundi", "257");
            listOfCountryCodes.Add("cambodia", "855");
            listOfCountryCodes.Add("cameroon", "237");
            listOfCountryCodes.Add("canada", "1");
            listOfCountryCodes.Add("cape Verde", "238");
            listOfCountryCodes.Add("cayman Islands", "1-345");
            listOfCountryCodes.Add("central African Republic", "236");
            listOfCountryCodes.Add("chad", "235");
            listOfCountryCodes.Add("chile", "56");
            listOfCountryCodes.Add("china", "86");
            listOfCountryCodes.Add("christmas island", "61");
            listOfCountryCodes.Add("cocos islands", "61");
            listOfCountryCodes.Add("colombia", "57");
            listOfCountryCodes.Add("comoros", "269");
            listOfCountryCodes.Add("cook islands", "682");
            listOfCountryCodes.Add("costa rica", "506");
            listOfCountryCodes.Add("croatia", "385");
            listOfCountryCodes.Add("cuba", "53");
            listOfCountryCodes.Add("curacao", "599");
            listOfCountryCodes.Add("cyprus", "357");
            listOfCountryCodes.Add("czech republic", "420");
            listOfCountryCodes.Add("democratic republic of the congo", "243");
            listOfCountryCodes.Add("denmark", "45");
            listOfCountryCodes.Add("djibouti", "253");
            listOfCountryCodes.Add("dominica", "1-767");
            listOfCountryCodes.Add("dominican republic1", "1-809");
            listOfCountryCodes.Add("dominican republic2", "1-829");
            listOfCountryCodes.Add("dominican republic3", "1-849");
            listOfCountryCodes.Add("east timor", "670");
            listOfCountryCodes.Add("ecuador", "593");
            listOfCountryCodes.Add("egypt", "20");
            listOfCountryCodes.Add("el salvador", "503");
            listOfCountryCodes.Add("equatorial guinea", "240");
            listOfCountryCodes.Add("eritrea", "291");
            listOfCountryCodes.Add("estonia", "372");
            listOfCountryCodes.Add("ethiopia", "251");
            listOfCountryCodes.Add("falkland islands", "500");
            listOfCountryCodes.Add("faroe islands", "298");
            listOfCountryCodes.Add("fiji", "679");
            listOfCountryCodes.Add("finland", "358");
            listOfCountryCodes.Add("france", "33");
            listOfCountryCodes.Add("french polynesia", "689");
            listOfCountryCodes.Add("gabon", "241");
            listOfCountryCodes.Add("gambia", "220");
            listOfCountryCodes.Add("georgia", "995");
            listOfCountryCodes.Add("germany", "49");
            listOfCountryCodes.Add("ghana", "233");
            listOfCountryCodes.Add("gibraltar", "350");
            listOfCountryCodes.Add("greece", "30");
            listOfCountryCodes.Add("greenland", "299");
            listOfCountryCodes.Add("grenada", "1-473");
            listOfCountryCodes.Add("guam", "1-671");
            listOfCountryCodes.Add("guatemala", "502");
            listOfCountryCodes.Add("guernsey", "44-1481");
            listOfCountryCodes.Add("guinea", "224");
            listOfCountryCodes.Add("guinea-bissau", "245");
            listOfCountryCodes.Add("guyana", "592");
            listOfCountryCodes.Add("haiti", "509");
            listOfCountryCodes.Add("honduras", "504");
            listOfCountryCodes.Add("hong kong", "852");
            listOfCountryCodes.Add("hungary", "36");
            listOfCountryCodes.Add("iceland", "354");
            listOfCountryCodes.Add("india", "91");
            listOfCountryCodes.Add("indonesia", "62");
            listOfCountryCodes.Add("iran", "98");
            listOfCountryCodes.Add("iraq", "964");
            listOfCountryCodes.Add("ireland", "353");
            listOfCountryCodes.Add("isle of man", "44-1624");
            listOfCountryCodes.Add("israel", "972");
            listOfCountryCodes.Add("italy", "39");
            listOfCountryCodes.Add("ivory coast", "225");
            listOfCountryCodes.Add("jamaica", "1-876");
            listOfCountryCodes.Add("japan", "81");
            listOfCountryCodes.Add("jersey", "44-1534");
            listOfCountryCodes.Add("jordan", "962");
            listOfCountryCodes.Add("kazakhstan", "7");
            listOfCountryCodes.Add("kenya", "254");
            listOfCountryCodes.Add("kiribati", "686");
            listOfCountryCodes.Add("kosovo", "383");
            listOfCountryCodes.Add("kuwait", "965");
            listOfCountryCodes.Add("kyrgyzstan", "996");
            listOfCountryCodes.Add("laos", "856");
            listOfCountryCodes.Add("latvia", "371");
            listOfCountryCodes.Add("lebanon", "961");
            listOfCountryCodes.Add("lesotho", "266");
            listOfCountryCodes.Add("liberia", "231");
            listOfCountryCodes.Add("libya", "218");
            listOfCountryCodes.Add("liechtenstein", "423");
            listOfCountryCodes.Add("lithuania", "370");
            listOfCountryCodes.Add("luxembourg", "352");
            listOfCountryCodes.Add("macau", "853");
            listOfCountryCodes.Add("macedonia", "389");
            listOfCountryCodes.Add("madagascar", "261");
            listOfCountryCodes.Add("malawi", "265");
            listOfCountryCodes.Add("malaysia", "60");
            listOfCountryCodes.Add("maldives", "960");
            listOfCountryCodes.Add("mali", "223");
            listOfCountryCodes.Add("malta", "356");
            listOfCountryCodes.Add("marshall islands", "692");
            listOfCountryCodes.Add("mauritania", "222");
            listOfCountryCodes.Add("mauritius", "230");
            listOfCountryCodes.Add("mayotte", "262");
            listOfCountryCodes.Add("mexico", "52");
            listOfCountryCodes.Add("micronesia", "691");
            listOfCountryCodes.Add("moldova", "373");
            listOfCountryCodes.Add("monaco", "377");
            listOfCountryCodes.Add("mongolia", "976");
            listOfCountryCodes.Add("montenegro", "382");
            listOfCountryCodes.Add("montserrat", "1-664");
            listOfCountryCodes.Add("morocco", "212");
            listOfCountryCodes.Add("mozambique", "258");
            listOfCountryCodes.Add("myanmar", "95");
            listOfCountryCodes.Add("namibia", "264");
            listOfCountryCodes.Add("nauru", "674");
            listOfCountryCodes.Add("nepal", "977");
            listOfCountryCodes.Add("netherlands", "31");
            listOfCountryCodes.Add("netherlands antilles", "599");
            listOfCountryCodes.Add("new caledonia", "687");
            listOfCountryCodes.Add("new zealand", "64");
            listOfCountryCodes.Add("nicaragua", "505");
            listOfCountryCodes.Add("niger", "227");
            listOfCountryCodes.Add("nigeria", "234");
            listOfCountryCodes.Add("niue", "683");
            listOfCountryCodes.Add("north korea", "850");
            listOfCountryCodes.Add("northern mariana islands", "1-670");
            listOfCountryCodes.Add("norway", "47");
            listOfCountryCodes.Add("oman", "968");
            listOfCountryCodes.Add("pakistan", "92");
            listOfCountryCodes.Add("palau", "680");
            listOfCountryCodes.Add("palestine", "970");
            listOfCountryCodes.Add("panama", "507");
            listOfCountryCodes.Add("papua new guinea", "675");
            listOfCountryCodes.Add("paraguay", "595");
            listOfCountryCodes.Add("peru", "51");
            listOfCountryCodes.Add("philippines", "63");
            listOfCountryCodes.Add("pitcairn", "64");
            listOfCountryCodes.Add("poland", "48");
            listOfCountryCodes.Add("portugal", "351");
            listOfCountryCodes.Add("puerto rico1", "1-787");
            listOfCountryCodes.Add("puerto rico2", "1-939");
            listOfCountryCodes.Add("qatar", "974");
            listOfCountryCodes.Add("republic of the congo", "242");
            listOfCountryCodes.Add("reunion", "262");
            listOfCountryCodes.Add("romania", "40");
            listOfCountryCodes.Add("russia", "7");
            listOfCountryCodes.Add("rwanda", "250");
            listOfCountryCodes.Add("saint barthelemy", "590");
            listOfCountryCodes.Add("saint helena", "290");
            listOfCountryCodes.Add("saint kitts and nevis", "1-869");
            listOfCountryCodes.Add("saint lucia", "1-758");
            listOfCountryCodes.Add("saint martin", "590");
            listOfCountryCodes.Add("saint pierre and miquelon", "508");
            listOfCountryCodes.Add("saint vincent and the grenadines", "1-784");
            listOfCountryCodes.Add("samoa", "685");
            listOfCountryCodes.Add("san marino", "378");
            listOfCountryCodes.Add("sao tome and principe", "239");
            listOfCountryCodes.Add("saudi arabia", "966");
            listOfCountryCodes.Add("senegal", "221");
            listOfCountryCodes.Add("serbia", "381");
            listOfCountryCodes.Add("seychelles", "248");
            listOfCountryCodes.Add("sierra leone", "232");
            listOfCountryCodes.Add("singapore", "65");
            listOfCountryCodes.Add("sint maarten", "1-721");
            listOfCountryCodes.Add("slovakia", "421");
            listOfCountryCodes.Add("slovenia", "386");
            listOfCountryCodes.Add("solomon islands", "677");
            listOfCountryCodes.Add("somalia", "252");
            listOfCountryCodes.Add("south africa", "27");
            listOfCountryCodes.Add("south korea", "82");
            listOfCountryCodes.Add("south sudan", "211");
            listOfCountryCodes.Add("spain", "34");
            listOfCountryCodes.Add("sri lanka", "94");
            listOfCountryCodes.Add("sudan", "249");
            listOfCountryCodes.Add("suriname", "597");
            listOfCountryCodes.Add("svalbard and jan mayen", "47");
            listOfCountryCodes.Add("swaziland", "268");
            listOfCountryCodes.Add("sweden", "46");
            listOfCountryCodes.Add("switzerland", "41");
            listOfCountryCodes.Add("syria", "963");
            listOfCountryCodes.Add("taiwan", "886");
            listOfCountryCodes.Add("tajikistan", "992");
            listOfCountryCodes.Add("tanzania", "255");
            listOfCountryCodes.Add("thailand", "66");
            listOfCountryCodes.Add("togo", "228");
            listOfCountryCodes.Add("tokelau", "690");
            listOfCountryCodes.Add("tonga", "676");
            listOfCountryCodes.Add("trinidad and tobago", "1-868");
            listOfCountryCodes.Add("tunisia", "216");
            listOfCountryCodes.Add("turkey", "90");
            listOfCountryCodes.Add("turkmenistan", "993");
            listOfCountryCodes.Add("turks and caicos islands", "1-649");
            listOfCountryCodes.Add("tuvalu", "688");
            listOfCountryCodes.Add("u.s. virgin islands", "1-340");
            listOfCountryCodes.Add("uganda", "256");
            listOfCountryCodes.Add("ukraine", "380");
            listOfCountryCodes.Add("united arab emirates", "971");
            listOfCountryCodes.Add("united kingdom", "44");
            listOfCountryCodes.Add("united states", "1");
            listOfCountryCodes.Add("uruguay", "598");
            listOfCountryCodes.Add("uzbekistan", "998");
            listOfCountryCodes.Add("vanuatu", "678");
            listOfCountryCodes.Add("vatican", "379");
            listOfCountryCodes.Add("venezuela", "58");
            listOfCountryCodes.Add("vietnam", "84");
            listOfCountryCodes.Add("wallis and futuna", "681");
            listOfCountryCodes.Add("western sahara", "212");
            listOfCountryCodes.Add("yemen", "967");
            listOfCountryCodes.Add("zambia", "260");
            listOfCountryCodes.Add("zimbabwe", "263");

            return listOfCountryCodes;
        }

        public static Dictionary<string, string> ListOfCountriesAndCodes()
        {
            return CountryAndPhoneCodeDataMethod();   
        }
    }
}
