using System;
using System.Collections.Generic;
using System.Text;

namespace Country_And_States_Telephone_Codes
{
    internal class CountryCodes
    {
        
        public static string GetCountryCodes(string country)
        {
            Dictionary<string, string> listOfCountryCodes = new Dictionary<string, string>();
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Albania", "355");
            listOfCountryCodes.Add("Algeria", "213");
            listOfCountryCodes.Add("American Samoa","1-684");
            listOfCountryCodes.Add("Andorra", "376");
            listOfCountryCodes.Add("Angola","244");
            listOfCountryCodes.Add("Anguilla",	"1-264");
            listOfCountryCodes.Add("Antarctica","672");
            listOfCountryCodes.Add("Antigua and Barbuda",	"1-268");
            listOfCountryCodes.Add("Argentina",	"54");
            listOfCountryCodes.Add("Armenia",	"374");
            listOfCountryCodes.Add("Aruba",	"297");
            listOfCountryCodes.Add("Australia",	"61");
            listOfCountryCodes.Add("Austria",	"43");
            listOfCountryCodes.Add("Azerbaijan", "994");
            listOfCountryCodes.Add("Azerbaijan", "994");
            listOfCountryCodes.Add("Bahamas", "1-242");
            listOfCountryCodes.Add("Bahrain", "973");
            listOfCountryCodes.Add("Bangladesh", "880");
            listOfCountryCodes.Add("Barbados",	"1-246");
            listOfCountryCodes.Add("Belarus",	"375");
            listOfCountryCodes.Add("Belgium",	"32");
            listOfCountryCodes.Add("Belize", "501");
            listOfCountryCodes.Add("Benin",	"229");
            listOfCountryCodes.Add("Bermuda",	"1-441");
            listOfCountryCodes.Add("Bhutan",	"975");
            listOfCountryCodes.Add("Bolivia",	"591");
            listOfCountryCodes.Add("Bosnia and Herzegovina", "387");
            listOfCountryCodes.Add("Botswana",	"267");
            listOfCountryCodes.Add("Brazil",	"55");
            listOfCountryCodes.Add("British Indian Ocean Territory",	"246");
            listOfCountryCodes.Add("British Virgin Islands",	"1-284");
            listOfCountryCodes.Add("Brunei",	"673");
            listOfCountryCodes.Add("Bulgaria",	"359");
            listOfCountryCodes.Add("Burkina Faso",	"226");
            listOfCountryCodes.Add("Burundi",	"257");
            listOfCountryCodes.Add("Cambodia",	"855");
            listOfCountryCodes.Add("Cameroon",	"237");
            listOfCountryCodes.Add("Canada",	"1");
            listOfCountryCodes.Add("Cape Verde",	"238");
            listOfCountryCodes.Add("Cayman Islands",	"1-345");
            listOfCountryCodes.Add("Central African Republic",	"236");
            listOfCountryCodes.Add("Chad",	"235");
            listOfCountryCodes.Add("Chile",	"56");
            listOfCountryCodes.Add("China",	"86");
            listOfCountryCodes.Add("Christmas Island",	"61");
            listOfCountryCodes.Add("Cocos Islands",	"61");
            listOfCountryCodes.Add("Colombia",	"57");
            listOfCountryCodes.Add("Comoros",	"269");
            listOfCountryCodes.Add("Cook Islands",	"682");
            listOfCountryCodes.Add("Costa Rica",	"506");
            listOfCountryCodes.Add("Croatia",	"385");
            listOfCountryCodes.Add("Cuba",	"53");
            listOfCountryCodes.Add("Curacao",	"599");
            listOfCountryCodes.Add("Cyprus",	"357");
            listOfCountryCodes.Add("Czech Republic",	"420");
            listOfCountryCodes.Add("Democratic Republic of the Congo",	"243");
            listOfCountryCodes.Add("Denmark",	"45");
            listOfCountryCodes.Add("Djibouti",	"253");
            listOfCountryCodes.Add("Dominica",	"1-767");
            listOfCountryCodes.Add("Dominican Republic",	"1-809");
            listOfCountryCodes.Add("Dominican Republic", "1-829");
            listOfCountryCodes.Add("Dominican Republic", "1-849");
            listOfCountryCodes.Add("East Timor",	"670");
            listOfCountryCodes.Add("Ecuador",	"593");
            listOfCountryCodes.Add("Egypt",	"20");
            listOfCountryCodes.Add("El Salvador",	"503");
            listOfCountryCodes.Add("Equatorial Guinea", "240");
            listOfCountryCodes.Add("Eritrea",	"291");
            listOfCountryCodes.Add("Estonia",	"372");
            listOfCountryCodes.Add("Ethiopia",	"251");
            listOfCountryCodes.Add("Falkland Islands", "500");
            listOfCountryCodes.Add("Faroe Islands",	"298");
            listOfCountryCodes.Add("Fiji",	"679");
            listOfCountryCodes.Add("Finland",	"358");
            listOfCountryCodes.Add("France", "33");
            listOfCountryCodes.Add("French Polynesia",	"689");
            listOfCountryCodes.Add("Gabon",	"241");
            listOfCountryCodes.Add("Gambia",	"220");
            listOfCountryCodes.Add("Georgia",	"995");
            listOfCountryCodes.Add("Germany",	"49");
            listOfCountryCodes.Add("Ghana",	"233");
            listOfCountryCodes.Add("Gibraltar",	"350");
            listOfCountryCodes.Add("Greece",	"30");
            listOfCountryCodes.Add("Greenland",	"299");
            listOfCountryCodes.Add("Grenada",	"1-473");
            listOfCountryCodes.Add("Guam",	"1-671");
            listOfCountryCodes.Add("Guatemala",	"502");
            listOfCountryCodes.Add("Guernsey",	"44-1481");
            listOfCountryCodes.Add("Guinea",	"224");
            listOfCountryCodes.Add("Guinea-Bissau",	"245");
            listOfCountryCodes.Add("Guyana",	"592");
            listOfCountryCodes.Add("Haiti",	"509");
            listOfCountryCodes.Add("Honduras",	"504");
            listOfCountryCodes.Add("Hong Kong", "852");
            listOfCountryCodes.Add("Hungary",	"36");
            listOfCountryCodes.Add("Iceland",	"354");
            listOfCountryCodes.Add("India",	"91");
            listOfCountryCodes.Add("Indonesia",	"62");
            listOfCountryCodes.Add("Iran",	"98");
            listOfCountryCodes.Add("Iraq",	"964");
            listOfCountryCodes.Add("Ireland",	"353");
            listOfCountryCodes.Add("Isle of Man",	"44-1624");
            listOfCountryCodes.Add("Israel",	"972");
            listOfCountryCodes.Add("Italy",	"39");
            listOfCountryCodes.Add("Ivory Coast",	"225");
            listOfCountryCodes.Add("Jamaica",	"1-876");
            listOfCountryCodes.Add("Japan",	"81");
            listOfCountryCodes.Add("Jersey",	"44-1534");
            listOfCountryCodes.Add("Jordan",	"962");
            listOfCountryCodes.Add("Kazakhstan",	"7");
            listOfCountryCodes.Add("Kenya",	"254");
            listOfCountryCodes.Add("Kiribati",	"686");
            listOfCountryCodes.Add("Kosovo",	"383");
            listOfCountryCodes.Add("Kuwait",	"965");
            listOfCountryCodes.Add("Kyrgyzstan",	"996");
            listOfCountryCodes.Add("Laos",	"856");
            listOfCountryCodes.Add("Latvia",	"371");
            listOfCountryCodes.Add("Lebanon",	"961");
            listOfCountryCodes.Add("Lesotho",	"266");
            listOfCountryCodes.Add("Liberia",	"231");
            listOfCountryCodes.Add("Libya",	"218");
            listOfCountryCodes.Add("Liechtenstein",	"423");
            listOfCountryCodes.Add("Lithuania",	"370");
            listOfCountryCodes.Add("Luxembourg",	"352");
            listOfCountryCodes.Add("Macau",	"853");
            listOfCountryCodes.Add("Macedonia",	"389");
            listOfCountryCodes.Add("Madagascar",	"261");
            listOfCountryCodes.Add("Malawi",	"265");
            listOfCountryCodes.Add("Malaysia",	"60");
            listOfCountryCodes.Add("Maldives",	"960");
            listOfCountryCodes.Add("Mali",	"223");
            listOfCountryCodes.Add("Malta",	"356");
            listOfCountryCodes.Add("Marshall Islands",	"692");
            listOfCountryCodes.Add("Mauritania",	"222");
            listOfCountryCodes.Add("Mauritius",	"230");
            listOfCountryCodes.Add("Mayotte",	"262");
            listOfCountryCodes.Add("Mexico",	"52");
            listOfCountryCodes.Add("Micronesia",	"691");
            listOfCountryCodes.Add("Moldova",	"373");
            listOfCountryCodes.Add("Monaco",	"377");
            listOfCountryCodes.Add("Mongolia",	"976");
            listOfCountryCodes.Add("Montenegro",	"382");
            listOfCountryCodes.Add("Montserrat",	"1-664");
            listOfCountryCodes.Add("Morocco",	"212");
            listOfCountryCodes.Add("Mozambique",	"258");
            listOfCountryCodes.Add("Myanmar",	"95");
            listOfCountryCodes.Add("Namibia",	"264");
            listOfCountryCodes.Add("Nauru",	"674");
            listOfCountryCodes.Add("Nepal",	"977");
            listOfCountryCodes.Add("Netherlands",	"31");
            listOfCountryCodes.Add("Netherlands Antilles",	"599");
            listOfCountryCodes.Add("New Caledonia",	"687");
            listOfCountryCodes.Add("New Zealand",	"64");
            listOfCountryCodes.Add("Nicaragua",	"505");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");
            listOfCountryCodes.Add("Afghanistan", "93");


            string countryCode = " ";


            return countryCode;
        }
    }
}
